### ISSUE TITLE
Project Status & Quality Check

### ISSUE THREAD

**Issue by app-generator** [app-generator/devtool-django-api-generator#1]
> This is used to track the overall progress of the project. 

Quality Check

- The new features are added using isolated assets
- The new assets are saved in `/static/assets/` using suggestive names 
- The JS code should be 100% Vanilla JS 
- No deprecated or jQuery-related dependencies.

**Comment by app-generator** [comment]
Hello @Mortrest 

The feature is migrated (with some minor improvements) here:

https://github.com/app-generator/django-soft-ui-dashboard/invitations

After tests, the API generator fails on two use cases: 

- add new fields to existing model 
- add a new model 

The development will be continued on the mentioned repo

ty!

**Comment by app-generator** [comment]
Hello @Mortrest

Let me know if any evolutions are pending, just to know to schedule the project for full tests. 

Ty!

**Comment by Mortrest** [comment]
Hello
No
api-view.html is also updated and is ready to use.

**Comment by app-generator** [comment]
cool. ty 
🚀🚀

**Comment by app-generator** [comment]
Validated & Closed.
