### ISSUE TITLE
New models DB migration issue

### ISSUE THREAD

**Issue by app-generator** [app-generator/devtool-django-api-generator#5]
Hello @Mortrest 

On fresh install of the project the new models defined are not migrated by following the steps suggested in the README. 

### How to reproduce: 

- clone a fresh clone
- create ENV & install dependencies -> **OK**
- execute the migration steps
  - `python.exe .\manage.py makemigrations` -> **OK**  
  - `python.exe .\manage.py migrate` -> **OK**
> Note: at this point the new tables defined in `apps/models` are not migrated.
- Generate API command warns the user for missing tables
  - `python manage.py generate-api`

```log
There are some models that aren't migrated:
['Book', 'Person', 'City']
``` 

Please provide a patch for this blocking case and also update README with a missing step (if is the case). 

Ty!

**Comment by Mortrest** [comment]
Hi
The reason of this issue is the migrations directory doesn't exist in `apps/` path. To solve this problem we have to options. First, Mention `apps` app after `makemigrations` command (`python manage.py makemigrations apps`). Second, Create an empty dicrectory in name of migrations in `apps/` path.
I use second solution to be more general.

**Comment by app-generator** [comment]
Hello @Mortrest 

`migrations` dir are ignored by `.gitignore`.

Please make it usable the `python manage.py makemigrations apps` CMD.

Ty!

**Comment by Mortrest** [comment]
I added this command to `README.md`. please update.

**Comment by app-generator** [comment]
perfect .. ty @Mortrest

**Comment by app-generator** [comment]
Hello @Mortrest 

Development moved to:
https://github.com/app-generator/django-soft-ui-dashboard

**Comment by app-generator** [comment]
Validated & Closed.
