### ISSUE TITLE
Books Creation - Fails with 'Authentication credentials were not provided'

### ISSUE THREAD

**Issue by app-generator** [app-generator/devtool-django-api-generator#6]
> Symptom: `Books` creation rejected with `Authentication credentials were not provided`

## How to reproduce

- Run the setup as suggested in README -> ok
- Use POSTMAN to generate token -> ok
  - login request -> `"token": "eb96a290d5b05f3971ea710e7df6f624cb6d0c0e"`
- Create a book -> **NOT_OK**

---

> **POST Request HEADER**

![image](https://user-images.githubusercontent.com/51070104/190214190-8cf65640-fe32-4dd4-aca1-2c25ce6496fa.png)

---

> **POST Request Body**

![image](https://user-images.githubusercontent.com/51070104/190214365-4edfd0c8-9a47-4b2f-98bc-539acd99513b.png)

---

> **Response**

![image](https://user-images.githubusercontent.com/51070104/190214463-b21ca669-133a-43c7-97b9-bfe21f4bbcd5.png)

---

Please advice. Ty!

**Comment by Mortrest** [comment]
Excuse me, I made a mistake in writing the readme.
the header authentication key is `Authorization`. I will correct readme descriptions.

**Comment by Mortrest** [comment]
Please update.

**Comment by app-generator** [comment]
🚀🚀

**Comment by app-generator** [comment]
The new response:
![image](https://user-images.githubusercontent.com/51070104/190224117-7a636143-2f48-43bd-8bc3-52e33dd7c056.png)

**Comment by app-generator** [comment]
Might be a good idea to export your POSTMAN collection used for tests and save it in the `media` directory.
Is much easier to synchronize all fields.

**Comment by Mortrest** [comment]
Hi
You should send field in form-data tab.
This is json link of my Postman collection: https://www.getpostman.com/collections/4797be9b8d8145c818f0
Please import it into your workspace and test codes.

**Comment by app-generator** [comment]
Works like a charm. 
Ty @Mortrest

**Comment by app-generator** [comment]
Hello @Mortrest 

Development moved to:
https://github.com/app-generator/django-soft-ui-dashboard

**Comment by app-generator** [comment]
Validated & Closed.
